// File generated by FlutterFire CLI.
// ─────────────────────────────────────────────────────────────────────────────
// HOW TO GENERATE THIS FILE:
//
// 1. Install the FlutterFire CLI (once per machine):
//      dart pub global activate flutterfire_cli
//
// 2. Log in to Firebase:
//      firebase login
//
// 3. From the project root, run:
//      flutterfire configure
//
//    Follow the prompts to select your Firebase project and target platforms.
//    The CLI will generate this file automatically with real values.
//
// ─────────────────────────────────────────────────────────────────────────────
// ⚠️  DO NOT commit real API keys to version control.
//    Add firebase_options.dart to .gitignore if it contains sensitive data,
//    or use environment variables / CI secrets.
// ─────────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── Android ─────────────────────────────────────────────────────────────
  // Values from android/app/google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCop8-t-igl8MT3w3OQjIV2LmqDhZvYlMQ',
    appId: '1:934105443254:android:a027add3d694074b6eef17',
    messagingSenderId: '934105443254',
    projectId: 'dinapp-3eadd',
    storageBucket: 'dinapp-3eadd.firebasestorage.app',
  );

  // ── iOS ──────────────────────────────────────────────────────────────────
  // Values from ios/Runner/GoogleService-Info.plist
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5LNGxFd3xb22QWMbVoGvQN21Pw-EsDfs',
    appId: '1:934105443254:ios:2458c6872d117a416eef17',
    messagingSenderId: '934105443254',
    projectId: 'dinapp-3eadd',
    storageBucket: 'dinapp-3eadd.firebasestorage.app',
    iosClientId: '934105443254-ajq2q6m9mq26e8krfr10a9b6q2ul7opf.apps.googleusercontent.com',
    iosBundleId: 'com.manbar.manbarAlmasjid',
  );

  // ── Web ──────────────────────────────────────────────────────────────────
  // Values from firebase apps:sdkconfig WEB
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyEDWS-jl_hKOw-LttYuxTQ_HN5P_Pe7I',
    appId: '1:934105443254:web:7517f56ebb91310d6eef17',
    messagingSenderId: '934105443254',
    projectId: 'dinapp-3eadd',
    authDomain: 'dinapp-3eadd.firebaseapp.com',
    storageBucket: 'dinapp-3eadd.firebasestorage.app',
    measurementId: 'G-TYM3VPXG9X',
  );
}


