import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

/// Central localization helper class for the app.
class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      // General
      'app_title': 'صلاتي قربك',
      'splash_subtitle': 'اعرف أقرب المساجد وأوقات الصلاة',
      'error_occurred': 'حدث خطأ',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'loading': 'جاري التحميل...',
      'retry': 'إعادة المحاولة',
      'soon': 'قريباً',
      'guest_badge': 'حساب زائر',
      'anonymous': 'زائر',
      'yes': 'نعم',
      'no': 'لا',
      'read_more': 'قراءة المزيد',
      'role_worshipper': 'مُصلٍّ',
      'role_imam': 'إمام / خطيب',
      'select_role': 'نوع الحساب',
      'add_mosque_title': 'إضافة مسجد إلى الخريطة',
      'add_mosque_btn': 'إضافة المسجد',
      'mosque_name_label': 'اسم المسجد / الجامع',
      'mosque_name_hint': 'مثال: جامع الملك فهد',
      'mosque_name_req': 'يرجى كتابة اسم المسجد',
      'mosque_address_label': 'العنوان / الحي',
      'mosque_address_hint': 'مثال: حي النخيل، الشارع العام',
      'mosque_search_address': 'ابحث عن عنوان أو مكان...',
      'mosque_search_address_label': 'ابحث عن موقع المسجد',
      'mosque_search_hint': 'اكتب اسم المكان أو العنوان',
      'mosque_search_no_results': 'لا توجد نتائج',
      'mosque_search_searching': 'جار البحث...',
      'mosque_location_confirm': 'تأكيد الموقع',
      'mosque_city_label': 'المدينة',
      'mosque_city_hint': 'مثال: الرياض',
      'mosque_country_label': 'الدولة',
      'mosque_capacity_label': 'السعة التقريبية (اختياري)',
      'mosque_capacity_hint': 'مثال: 500',
      'mosque_phone_label': 'رقم التواصل (اختياري)',
      'mosque_location_picker': 'حدد موقع المسجد على الخريطة',
      'mosque_locate_me': 'موقعي الحالي',
      'mosque_add_success': 'تمت إضافة المسجد بنجاح وجعله متاحاً على الخريطة!',
      'claim_mosque_title': 'ربط مسجدي كإمام',
      'claim_mosque_subtitle': 'ابحث عن مسجدك على الخريطة لربط حسابك به',
      'claim_mosque_search_hint': 'ابحث باسم المسجد أو المدينة...',
      'claim_this_mosque': 'تأكيد وربط هذا المسجد',
      'mosque_claimed_by_other': 'مرتبط بإمام آخر',
      'mosque_not_found_prompt': 'لم تجد مسجدك في القائمة؟',
      'add_new_mosque_btn': 'أضف مسجداً جديداً',
      'claim_success': 'تم ربط المسجد بحسابك كإمام بنجاح!',
      'add_mosque_fab': 'أضف مسجداً',
      'my_mosque_card': 'مسجدي كإمام',

      // Bottom Navigation Bar
      'nav_home': 'الرئيسية',
      'nav_prayer_times': 'أوقات الصلاة',
      'nav_mosques': 'المساجد',
      'nav_posts': 'المنشورات',
      'nav_ask': 'اسأل',
      'nav_profile': 'الملف الشخصي',

      // Home Screen
      'next_prayer': 'الصلاة القادمة',
      'prayers_ended': 'انتهت صلوات اليوم',
      'remaining_time': 'الوقت المتبقي: ',
      'today_prayer_times': 'مواقيت اليوم',
      'notifications': 'الإشعارات',
      'sign_out': 'تسجيل الخروج',
      
      // Prayer Names
      'Fajr': 'الفجر',
      'Sunrise': 'الشروق',
      'Dhuhr': 'الظهر',
      'Asr': 'العصر',
      'Maghrib': 'المغرب',
      'Isha': 'العشاء',
      'الفجر': 'الفجر',
      'الشروق': 'الشروق',
      'الظهر': 'الظهر',
      'العصر': 'العصر',
      'المغرب': 'المغرب',
      'العشاء': 'العشاء',

      // Profile Screen
      'profile_title': 'الملف الشخصي',
      'incoming_questions': 'الأسئلة الواردة (للأئمة)',
      'followed_mosques': 'المساجد المتابعة',
      'preferences': 'التفضيلات',
      'adhan_sound_settings': 'صوت الأذان والتنبيهات',
      'adhan_sound_settings_desc': 'تخصيص مؤذن وتنبيهات أوقات الصلاة',
      'choose_adhan_sound': 'اختر صوت الأذان المفضل',
      'adhan_mute_toggle_title': 'كتم صوت الأذان (إشعارات فقط)',
      'adhan_mute_toggle_desc': 'تلقي إشعارات وتنبيه مرئي بالصلاة دون تشغيل صوت الأذان',
      'preview_adhan': 'استماع',
      'stop_preview': 'إيقاف',
      'selected': 'محدد',
      'select': 'اختيار',
      'custom_prayer_sounds': 'تخصيص صوت لكل صلاة',
      'custom_prayer_sounds_desc': 'تحديد أذان مختلف لصلاة الفجر أو صلوات محددة',
      'sound_applied_all': 'تم تعيين صوت الأذان لجميع الصلوات بنجاح',
      'sound_applied_prayer': 'تم تعيين صوت الأذان لصلاة {prayer}',
      'adhan_muted_msg': 'تم كتم صوت الأذان (إشعار فقط)',
      'adhan_unmuted_msg': 'تم تفعيل صوت الأذان',
      'test_instant_alert': 'تجربة الإشعار وتنبيه الأذان',
      'test_1min_alarm': 'تجربة المنبه بعد دقيقة (شاشة مقفلة)',
      'test_1min_scheduled': 'تم جدولة منبه تجريبي بعد دقيقة! يمكنك إغلاق الشاشة الآن للتجربة ⏱️',
      'language': 'اللغة',
      'about_app': 'حول التطبيق',
      'about_salati': 'عن صلاتي قربك',
      'privacy_policy': 'سياسة الخصوصية',
      'delete_account': 'حذف الحساب',
      
      // Dialogs / Sheet
      'confirm_sign_out': 'تأكيد تسجيل الخروج',
      'confirm_sign_out_desc': 'هل أنت متأكد من رغبتك في تسجيل الخروج؟',
      'confirm_delete_account': 'تأكيد حذف الحساب',
      'confirm_delete_desc': 'تحذير: هذا الإجراء نهائي وسيتم حذف جميع بياناتك.',
      'delete': 'حذف',
      'select_language': 'اختر لغتك المفضلة',
      'language_arabic': 'العربية',
      'language_english': 'English',

      // Guest sheet / Guest banner
      'guest_upgrade_title': 'أنشئ حساباً للمتابعة والتفاعل',
      'guest_upgrade_desc': 'لتتمكن من تسجيل الإعجاب، التعليق، ومتابعة الأئمة والمساجد والمزيد.',
      'create_account': 'إنشاء حساب',
      'sign_in': 'تسجيل الدخول',
      'upgrade_title': 'أنشئ حساباً للمتابعة',
      'upgrade_subtitle': 'قم بالتسجيل لمتابعة المساجد والتفاعل',
      'register_btn': 'تسجيل',

      // Login Screen
      'login_google_failed': 'فشل تسجيل الدخول عبر Google',
      'login_apple_failed': 'فشل تسجيل الدخول عبر Apple',
      'login_guest_failed': 'فشل الدخول كزائر',
      'welcome': 'مرحباً بك',
      'login_subtitle': 'سجّل الدخول لمتابعة مسجدك المفضل',
      'email': 'البريد الإلكتروني',
      'email_required': 'أدخل البريد الإلكتروني',
      'email_invalid': 'البريد الإلكتروني غير صالح',
      'password': 'كلمة المرور',
      'password_required': 'أدخل كلمة المرور',
      'password_too_short': 'يجب أن تكون 6 أحرف على الأقل',
      'forgot_password_question': 'نسيت كلمة المرور؟',
      'login_btn': 'تسجيل الدخول',
      'or': 'أو',
      'continue_as_guest': 'المتابعة كزائر',
      'no_account_question': 'ليس لديك حساب؟',
      'copyright': '© 2025 صلاتي قربك – جميع الحقوق محفوظة',
      'reset_password_title': 'إعادة تعيين كلمة المرور',
      'reset_password_subtitle': 'أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين.',
      'send': 'إرسال',
      'reset_email_sent': 'تم إرسال رابط إعادة تعيين كلمة المرور إلى {email}',


      // Nearby Mosques Screen
      'nearby_mosques_title': 'المساجد القريبة',
      'map_view': 'عرض الخريطة',
      'list_view': 'عرض القائمة',
      'search_mosque': 'ابحث عن مسجد...',
      'search_placeholder': 'ابحث باسم المسجد أو العنوان...',
      'radius_limit_label': 'النطاق الجغرافي:',
      'unfollowed_mosque': 'تم إلغاء متابعة "{name}"',
      'followed_mosque_success': 'أنت الآن تتابع "{name}" ✓',

      'maps_launch_failed': 'فشل فتح تطبيق الخرائط.',
      'load_error_prefix': 'حدث خطأ في تحميل البيانات: ',
      'no_mosques_found': 'لم يتم العثور على مساجد في هذا النطاق.',

      // Saved Mosques Screen
      'saved_mosques_title': 'المساجد المتابعة',
      'failed_load_saved_mosques': 'فشل تحميل قائمة المساجد',
      'unfollow_success': 'تم إلغاء متابعة المسجد',
      'unfollow_dialog_title': 'إلغاء المتابعة',
      'unfollow_dialog_desc': 'هل تريد إلغاء متابعة "{name}"؟',

      'unfollow_confirm_btn': 'نعم، إلغاء المتابعة',
      'no_followed_mosques': 'لا توجد مساجد متابَعة',
      'no_followed_desc': 'تابع المساجد القريبة منك لتصلك أوقات الصلاة والمنشورات مباشرة.',
      'explore_nearby': 'اكتشف المساجد القريبة',
      'member_feature_title': 'هذه الميزة للأعضاء',
      'member_feature_desc': 'أنشئ حساباً للمتابعة والتفاعل والاستفادة من جميع الميزات.',
      'browse_without_account': 'تصفح بدون حساب',

      // Shared UI units & labels
      'km': 'كم',
      'meters': 'م',
      'distance': 'تبعد',
      'open': 'مفتوح',
      'follow': 'متابعة',
      'following': 'متابع',
      'directions': 'الاتجاهات',
      'details': 'التفاصيل',

      // Prayer Times Screen
      'prayer_times_title': 'مواقيت الصلاة',
      'by_my_location': 'حسب موقعي',
      'by_mosque_location': 'حسب مسجد',
      'alert_enabled': 'تم تفعيل التنبيه لـ {name}',
      'alert_disabled': 'تم إلغاء التنبيه لـ {name}',
      'test_adhan_tooltip': 'تجربة صوت الأذان',
      'test_adhan_sent': 'تم إرسال إشعار تجريبي بصوت الأذان 🕌',
      'ongoing_prayer_bar': 'الشريط الدائم لمواقيت الصلاة',
      'ongoing_prayer_bar_desc': 'عرض التاريخ الهجري وموعد الصلاة القادمة في شريط الإشعارات',
      'hijri_suffix': 'هـ',
      'prayer_bell_tooltip': 'تنبيه الأذان',
      'prayer_load_failed': 'فشل تحميل أوقات الصلاة',
      'prayer_enable_location': 'أدخل موقعك الجغرافي أولاً',
      'prayer_select_mosque': 'الرجاء اختيار مسجد لعرض الأوقات الرسمية',
      'prayer_mosque_load_failed': 'خطأ في تحميل أوقات هذا المسجد',
      'prayer_no_times_set': 'لم يتم إدخال مواقيت صلاة لهذا اليوم من قبل إدارة هذا المسجد.',
      'prayer_no_nearby_mosques': 'لا توجد مساجد قريبة متوفرة',
      'prayer_source': 'المصدر: الإمام {name}',
      'jumuah_label': 'صلاة الجمعة بالمسجد',

      // Hijri months

      'hijri_muharram': 'محرم',
      'hijri_safar': 'صفر',
      'hijri_rabi1': 'ربيع الأول',
      'hijri_rabi2': 'ربيع الآخر',
      'hijri_jumada1': 'جمادى الأولى',
      'hijri_jumada2': 'جمادى الآخرة',
      'hijri_rajab': 'رجب',
      'hijri_shaban': 'شعبان',
      'hijri_ramadan': 'رمضان',
      'hijri_shawwal': 'شوال',
      'hijri_dhulqada': 'ذو القعدة',
      'hijri_dhulhijja': 'ذو الحجة',

      // Days & Gregorian months
      'day_mon': 'الإثنين',
      'day_tue': 'الثلاثاء',
      'day_wed': 'الأربعاء',
      'day_thu': 'الخميس',
      'day_fri': 'الجمعة',
      'day_sat': 'السبت',
      'day_sun': 'الأحد',
      'month_jan': 'يناير',
      'month_feb': 'فبراير',
      'month_mar': 'مارس',
      'month_apr': 'أبريل',
      'month_may': 'مايو',
      'month_jun': 'يونيو',
      'month_jul': 'يوليو',
      'month_aug': 'أغسطس',
      'month_sep': 'سبتمبر',
      'month_oct': 'أكتوبر',
      'month_nov': 'نوفمبر',
      'month_dec': 'ديسمبر',

      // Feed Screen
      'feed_title': 'المنشورات والمستجدات',
      'tab_all': 'الكل',
      'tab_followed': 'المتابَعة',
      'unsave_post_success': 'تم إلغاء حفظ المنشور',
      'save_post_success': 'تم حفظ المنشور ✓',
      'feed_load_posts_failed': 'فشل تحميل المنشورات',
      'no_posts_category': 'لا توجد منشورات في هذه الفئة',
      'no_posts_followed': 'لا توجد منشورات من المساجد والأئمة المتابَعين بعد',
      'feed_no_followed_title': 'لا تتابع أي مسجد أو إمام بعد',
      'feed_no_followed_desc': 'تابع المساجد القريبة منك وأئمتها لتظهر منشوراتهم هنا مباشرةً.',
      'feed_guest_title': 'هذه الميزة للأعضاء',
      'feed_guest_desc': 'أنشئ حساباً لمتابعة المساجد ورؤية منشوراتها هنا.',
      'feed_elapsed_minute': 'منذ {count} دقيقة',
      'feed_elapsed_hour': 'منذ {count} ساعة',
      'feed_elapsed_day': 'منذ {count} يوم',
      'feed_like_tooltip': 'إعجاب',
      'feed_comment_tooltip': 'تعليق',
      'feed_save_tooltip': 'حفظ المنشور',
      'feed_unsave_tooltip': 'إلغاء الحفظ',
      'feed_share_tooltip': 'مشاركة',
      'feed_general_post': 'عام',
      'cat_all': 'الكل',
      'cat_nearby': 'قريب مني',
      'cat_lessons': 'دروس',
      'cat_announcements': 'إعلانات',
      'cat_activities': 'أنشطة',

      // Mosque Details Screen
      'mosque_load_error': 'خطأ في تحميل بيانات المسجد',
      'mosque_not_found': 'المسجد غير موجود',
      'mosque_share_copied': 'تم نسخ اسم المسجد',
      'mosque_unfollow_snack': 'تم إلغاء متابعة "المسجد"',
      'mosque_follow_snack': 'أنت الآن تتابع "المسجد" ✓',
      'imam_unfollow_snack': 'تم إلغاء متابعة الإمام',
      'imam_follow_snack': 'أنت الآن تتابع الإمام ✓',
      'share': 'مشاركة',
      'verified_mosque': 'مسجد موثّق',
      'today_times': 'مواقيت اليوم',
      'imam_label': 'الإمام: {name}',
      'no_times_today': 'لا توجد أوقات محددة لهذا اليوم',
      'next_badge': 'التالية',
      'prayer_times_tab': 'أوقات الصلاة',
      'posts_tab': 'المنشورات',
      'about_mosque_tab': 'عن المسجد',
      'prayer_times_error': 'خطأ في تحميل المواقيت',
      'no_prayer_times_today': 'لا توجد أوقات صلاة لهذا اليوم',
      'imam_updates_daily': 'يقوم الإمام بتحديث الأوقات يومياً',
      'prayer_source_imam': 'المصدر: الإمام {name}',
      'jumuah_friday': 'صلاة الجمعة',
      'posts_load_failed': 'فشل تحميل المنشورات',
      'no_mosque_posts': 'لا توجد منشورات لهذا المسجد بعد',
      'save_post_snack': 'تم حفظ المنشور ✓',
      'unsave_post_snack': 'تم إلغاء حفظ المنشور',
      'mosque_my_mosques': 'مساجدي',
      'mosque_follow_btn': 'متابعة المسجد',
      'imam_follow_btn': 'متابعة الإمام',
      'imam_following_btn': 'متابع للإمام',
      'info_address': 'العنوان',
      'info_phone': 'رقم الاتصال',
      'info_capacity': 'السعة الاستيعابية',
      'capacity_unit': 'مصلٍّ',
      'info_city': 'المدينة',
      'info_verified': 'حالة التوثيق',
      'mosque_verified_yes': 'مسجد موثَّق ✓',
      'mosque_verified_no': 'غير موثَّق',
      'info_date_added': 'تاريخ الإضافة',

      // Post Details Screen
      'post_not_found': 'لم يتم العثور على المنشور',
      'likes_count': '{count} إعجاب',
      'comments_count': '{count} تعليق',
      'comments_title': 'التعليقات',
      'copy_post_snack': 'تم نسخ المنشور',
      'saved_snack': 'تم الحفظ ✓',
      'share_post': 'مشاركة',
      'view_mosque': 'عرض المسجد',
      'event_details': 'تفاصيل الفعالية',
      'event_date': 'التاريخ',
      'event_time': 'الوقت',
      'event_location': 'الموقع',
      'comments_load_failed': 'فشل تحميل التعليقات',
      'no_comments_yet': 'لا توجد تعليقات بعد. كن أول من يعلق!',
      'elapsed_now': 'الآن',
      'elapsed_minutes': 'منذ {count} دقيقة',
      'elapsed_hours': 'منذ {count} ساعة',
      'elapsed_days': 'منذ {count} يوم',
      'comment_limit_error': 'الحد الأقصى للتعليق هو 500 حرف',
      'comment_hint': 'اكتب تعليقاً...',
      'comment_added': 'تم إضافة التعليق بنجاح ✓',
      'comment_failed': 'فشل إضافة التعليق',
      'imam_mosque_label': 'إمام المسجد: {name}',
      'post_follow_btn': 'متابعة',
      'post_following_btn': 'متابع',
      'mosque_label_default': 'مسجد',

      // Register Screen
      'register_title': 'إنشاء حساب',
      'register_subtitle': 'انضم إلى صلاتي قربك واعرف مسجدك',
      'full_name': 'الاسم الكامل',
      'full_name_hint': 'محمد أحمد',
      'full_name_required': 'أدخل اسمك الكامل',
      'phone_optional': 'رقم الهاتف (اختياري)',
      'confirm_password': 'تأكيد كلمة المرور',
      'confirm_password_required': 'أكّد كلمة المرور',
      'passwords_mismatch': 'كلمتا المرور غير متطابقتين',
      'city_optional': 'المدينة (اختياري)',
      'city_hint': 'الرياض',
      'create_account_btn': 'إنشاء الحساب',

      'continue_with_google': 'المتابعة عبر Google',
      'continue_with_apple': 'المتابعة عبر Apple',
      'already_have_account': 'لديك حساب بالفعل؟',
      'sign_in_link': 'تسجيل الدخول',
      'register_google_failed': 'فشل التسجيل عبر Google',
      'register_apple_failed': 'فشل التسجيل عبر Apple',

      // Profile screen extra keys
      'send_reset_email_label': 'إرسال رابط إعادة التعيين',
      'reset_email_sent_short': 'تم الإرسال ✓',
      'change_password': 'تغيير كلمة المرور',
      'change_email': 'تغيير البريد الإلكتروني',
      'guest_user': 'زائر',
      'member_since': 'عضو منذ',
      'sign_out_btn': 'تسجيل الخروج',
      'cancel_btn': 'إلغاء',
      'edit_name': 'تعديل الاسم',
      'new_name_hint': 'أدخل الاسم',
      'done_btn': 'تم',
      'app_name': 'صلاتي قربك',
      'app_legal': '© 2025 صلاتي قربك. جميع الحقوق محفوظة.',
      'delete_desc_full': 'هذا الإجراء نهائي وسيتم حذف جميع بياناتك من قواعد البيانات. هل أنت متأكد؟',
      'upgrade_account': 'تسجيل حساب',
      'guest_upgrade_prompt': 'أنشئ حساباً للمتابعة والتفاعل والاستفادة من جميع الميزات.',
      'reset_email_sent_to': 'سيتم إرسال رابط إعادة التعيين إلى:\n{email}',
      'registered_user': 'مستخدم مسجّل',
      'create_account_free': 'أنشئ حساباً مجاناً',
      'guest_upgrade_card_desc': 'احفظ تفضيلاتك، تابع مواعيد الصلاة وتواصل مع مساجدك المفضلة عبر جميع أجهزتك.',
      'guest_exit_btn': 'الخروج من وضع الزائر',
      'delete_account_confirm': 'هل أنت متأكد من حذف حسابك نهائياً؟ لا يمكن التراجع عن هذا الإجراء.',
      
      // Location Permission Screen
      'loc_my_location': 'موقعي الحالي',
      'loc_permission_failed': 'فشل الوصول للموقع الحالي. يرجى إدخاله يدوياً.',
      'loc_error': 'حدث خطأ أثناء تحديد الموقع.',
      'loc_title': 'تحديد موقعك الحالي',
      'loc_desc': 'لعرض أوقات الصلاة بدقة وتحديد أقرب المساجد، يحتاج التطبيق إلى الوصول لموقعك الجغرافي.',
      'loc_allow_btn': 'متابعة',
      'loc_manual_btn': 'إدخال الموقع يدوياً',
      'loc_select_city': 'اختر مدينتك',
      'loc_select_city_desc': 'اختر من المدن المتاحة لعرض أوقات الصلاة والمساجد القريبة منها.',
      'city_makkah': 'مكة المكرمة',
      'city_madinah': 'المدينة المنورة',
      'city_riyadh': 'الرياض',
      'city_jeddah': 'جدة',
      'city_dubai': 'دبي',
      'city_cairo': 'القاهرة',
      'city_casablanca': 'الدار البيضاء',
      'city_amman': 'عمان',

      // Home Screen extra
      'calc_method_label': 'طريقة الحساب: {method}',
      'calc_method_title': 'طريقة الحساب',
      'auto': 'تلقائي',
      'check_internet_retry': 'تحقق من اتصالك بالإنترنت ثم أعد المحاولة.',

      // Calculation Methods
      'method_1': 'هيئة الرصد الجوي الكويتية',
      'method_2': 'جامعة العلوم الإسلامية، كراتشي',
      'method_3': 'رابطة العالم الإسلامي (MWL)',
      'method_4': 'أم القرى، مكة المكرمة',
      'method_5': 'الهيئة المصرية العامة للمساحة',
      'method_7': 'اتحاد المنظمات الإسلامية في أمريكا الشمالية (ISNA)',
      'method_8': 'الخليج العربي',
      'method_9': 'ديانت إيشلري باشقانليغي (تركيا)',
      'method_10': 'الجزائر — وزارة الشؤون الدينية',
      'method_11': 'لجنة التحقق الوطنية (اندونيسيا)',
      'method_12': 'المجلس الإسلامي للفرنسيين في المناطق الشمالية',
      'method_13': 'المطالبة الرسمية العُمانية',
      'method_14': 'قطر — وزارة الشؤون الدينية',
      'method_15': 'سنغافورة',
      'method_16': 'اتحاد المنظمات الإسلامية في فرنسا (UOIF)',
      'method_17': 'دائرة الشؤون الدينية، كوالالمبور',
      'method_18': 'المغرب — وزارة الأوقاف',
      'method_19': 'الجامعة الإسلامية في الإمارات',
      'method_21': 'المجلس الأوروبي للإفتاء والبحوث',
      'method_22': 'الجمعية الإسلامية في أمريكا الشمالية (Canada)',
      'method_23': 'التقويم الرسمي — بنجلاديش',
      'method_24': 'هيئة أبوظبي للزراعة والسلامة الغذائية',
    },





    'en': {
      // General
      'app_title': 'Salati Qourbak',
      'splash_subtitle': 'Find nearby mosques and prayer times',
      'error_occurred': 'An error occurred',
      'cancel': 'Cancel',
      'save': 'Save',
      'loading': 'Loading...',
      'retry': 'Retry',
      'soon': 'Soon',
      'guest_badge': 'Guest Account',
      'anonymous': 'Guest',
      'yes': 'Yes',
      'no': 'No',
      'read_more': 'Read more',
      'role_worshipper': 'Worshipper',
      'role_imam': 'Imam / Preacher',
      'select_role': 'Account Type',
      'add_mosque_title': 'Add Mosque to Map',
      'add_mosque_btn': 'Add Mosque',
      'mosque_name_label': 'Mosque Name',
      'mosque_name_hint': 'e.g. Al-Noor Mosque',
      'mosque_name_req': 'Please enter the mosque name',
      'mosque_address_label': 'Address / District',
      'mosque_address_hint': 'e.g. Al-Nakheel, Main St',
      'mosque_search_address': 'Search for an address or place...',
      'mosque_search_address_label': 'Search mosque location',
      'mosque_search_hint': 'Type a place name or address',
      'mosque_search_no_results': 'No results found',
      'mosque_search_searching': 'Searching...',
      'mosque_location_confirm': 'Confirm Location',
      'mosque_city_label': 'City',
      'mosque_city_hint': 'e.g. Riyadh',
      'mosque_country_label': 'Country',
      'mosque_capacity_label': 'Capacity (Optional)',
      'mosque_capacity_hint': 'e.g. 500',
      'mosque_phone_label': 'Contact Phone (Optional)',
      'mosque_location_picker': 'Pick Mosque Location on Map',
      'mosque_locate_me': 'My Location',
      'mosque_add_success': 'Mosque added successfully to the map!',
      'claim_mosque_title': 'Link Mosque as Imam',
      'claim_mosque_subtitle': 'Search for your mosque on the map to link it to your account',
      'claim_mosque_search_hint': 'Search by mosque name or city...',
      'claim_this_mosque': 'Confirm & Link This Mosque',
      'mosque_claimed_by_other': 'Linked to another Imam',
      'mosque_not_found_prompt': 'Cannot find your mosque?',
      'add_new_mosque_btn': 'Add a New Mosque',
      'claim_success': 'Mosque linked to your account successfully!',
      'add_mosque_fab': 'Add Mosque',
      'my_mosque_card': 'My Mosque (Imam)',

      // Bottom Navigation Bar
      'nav_home': 'Home',
      'nav_prayer_times': 'Prayer Times',
      'nav_mosques': 'Mosques',
      'nav_posts': 'Posts',
      'nav_ask': 'Ask',
      'nav_profile': 'Profile',

      // Home Screen
      'next_prayer': 'Next Prayer',
      'prayers_ended': 'Prayers ended for today',
      'remaining_time': 'Time remaining: ',
      'today_prayer_times': 'Today\'s Times',
      'notifications': 'Notifications',
      'sign_out': 'Sign Out',

      // Prayer Names
      'Fajr': 'Fajr',
      'Sunrise': 'Sunrise',
      'Dhuhr': 'Dhuhr',
      'Asr': 'Asr',
      'Maghrib': 'Maghrib',
      'Isha': 'Isha',
      'الفجر': 'Fajr',
      'الشروق': 'Sunrise',
      'الظهر': 'Dhuhr',
      'العصر': 'Asr',
      'المغرب': 'Maghrib',
      'العشاء': 'Isha',

      // Profile Screen
      'profile_title': 'Profile',
      'incoming_questions': 'Incoming Questions (Imams)',
      'followed_mosques': 'Followed Mosques',
      'preferences': 'Preferences',
      'adhan_sound_settings': 'Adhan Sound & Alerts',
      'adhan_sound_settings_desc': 'Customize muezzin & prayer alert sounds',
      'choose_adhan_sound': 'Choose your preferred Adhan sound',
      'adhan_mute_toggle_title': 'Mute Adhan Audio (Notifications Only)',
      'adhan_mute_toggle_desc': 'Receive prayer alerts without playing any Adhan audio',
      'preview_adhan': 'Preview',
      'stop_preview': 'Stop',
      'selected': 'Selected',
      'select': 'Select',
      'custom_prayer_sounds': 'Custom Sound Per Prayer',
      'custom_prayer_sounds_desc': 'Set a different adhan for Fajr or specific prayers',
      'sound_applied_all': 'Adhan sound applied to all prayers',
      'sound_applied_prayer': 'Adhan sound applied for {prayer}',
      'adhan_muted_msg': 'Adhan audio muted (notifications only)',
      'adhan_unmuted_msg': 'Adhan audio enabled',
      'test_instant_alert': 'Test Adhan Alert Now',
      'test_1min_alarm': 'Test Background Alarm in 1 min',
      'test_1min_scheduled': 'Background alarm scheduled in 1 minute! Lock your screen to test ⏱️',
      'language': 'Language',
      'about_app': 'About App',
      'about_salati': 'About Salati Qourbak',
      'privacy_policy': 'Privacy Policy',
      'delete_account': 'Delete Account',

      // Dialogs / Sheet
      'confirm_sign_out': 'Confirm Sign Out',
      'confirm_sign_out_desc': 'Are you sure you want to sign out?',
      'confirm_delete_account': 'Confirm Delete Account',
      'confirm_delete_desc': 'Warning: This action is permanent and all your data will be deleted.',
      'delete': 'Delete',
      'select_language': 'Select your preferred language',
      'language_arabic': 'العربية',
      'language_english': 'English',

      // Guest sheet / Guest banner
      'guest_upgrade_title': 'Create a free account',
      'guest_upgrade_desc': 'Save your preferences and track times across devices.',
      'create_account': 'Create Account',
      'sign_in': 'Sign In',
      'upgrade_title': 'Unlock Full Access',
      'upgrade_subtitle': 'Create an account to follow mosques & interact',
      'register_btn': 'Register',

      // Login Screen
      'login_google_failed': 'Failed to sign in with Google',
      'login_apple_failed': 'Failed to sign in with Apple',
      'login_guest_failed': 'Failed to sign in as guest',
      'welcome': 'Welcome',
      'login_subtitle': 'Log in to follow your favorite mosque',
      'email': 'Email Address',
      'email_required': 'Please enter email address',
      'email_invalid': 'Invalid email address',
      'password': 'Password',
      'password_required': 'Please enter password',
      'password_too_short': 'Must be at least 6 characters',
      'forgot_password_question': 'Forgot password?',
      'login_btn': 'Sign In',
      'or': 'or',
      'continue_as_guest': 'Continue as Guest',
      'no_account_question': 'Don\'t have an account?',
      'copyright': '© 2025 Salati Qourbak – All rights reserved',
      'reset_password_title': 'Reset Password',
      'reset_password_subtitle': 'Enter your email to receive a password reset link.',
      'send': 'Send',
      'reset_email_sent': 'Password reset link sent to {email}',


      // Nearby Mosques Screen
      'nearby_mosques_title': 'Nearby Mosques',
      'map_view': 'Map View',
      'list_view': 'List View',
      'search_mosque': 'Search for a mosque...',
      'search_placeholder': 'Search by mosque name or address...',
      'radius_limit_label': 'Search Radius:',
      'unfollowed_mosque': 'Unfollowed "{name}"',
      'followed_mosque_success': 'You are now following "{name}" ✓',

      'maps_launch_failed': 'Failed to open maps application.',
      'load_error_prefix': 'An error occurred loading data: ',
      'no_mosques_found': 'No mosques found in this range.',

      // Saved Mosques Screen
      'saved_mosques_title': 'Followed Mosques',
      'failed_load_saved_mosques': 'Failed to load mosques list',
      'unfollow_success': 'Unfollowed mosque successfully',
      'unfollow_dialog_title': 'Unfollow Mosque',
      'unfollow_dialog_desc': 'Do you want to unfollow "{name}"?',

      'unfollow_confirm_btn': 'Yes, Unfollow',
      'no_followed_mosques': 'No followed mosques',
      'no_followed_desc': 'Follow nearby mosques to receive prayer times and community posts directly.',
      'explore_nearby': 'Explore Nearby Mosques',
      'member_feature_title': 'Member-only Feature',
      'member_feature_desc': 'Create an account to follow, interact, and benefit from all features.',
      'browse_without_account': 'Browse as Guest',

      // Shared UI units & labels
      'km': 'km',
      'meters': 'm',
      'distance': 'Distance',
      'open': 'Open',
      'follow': 'Follow',
      'following': 'Following',
      'directions': 'Directions',
      'details': 'Details',

      // Prayer Times Screen
      'prayer_times_title': 'Prayer Times',
      'by_my_location': 'By Location',
      'by_mosque_location': 'By Mosque',
      'alert_enabled': 'Alert enabled for {name}',
      'alert_disabled': 'Alert cancelled for {name}',
      'test_adhan_tooltip': 'Test Adhan Sound',
      'test_adhan_sent': 'Test Adhan notification sent 🕌',
      'ongoing_prayer_bar': 'Persistent Prayer Status Bar',
      'ongoing_prayer_bar_desc': 'Display Hijri date and next prayer in the notification shade',
      'hijri_suffix': 'AH',
      'prayer_bell_tooltip': 'Prayer Alert',
      'prayer_load_failed': 'Failed to load prayer times',
      'prayer_enable_location': 'Enable your location first',
      'prayer_select_mosque': 'Please select a mosque to view official times',
      'prayer_mosque_load_failed': 'Error loading this mosque\'s times',
      'prayer_no_times_set': 'Prayer times for today have not been entered by this mosque\'s administration.',
      'prayer_no_nearby_mosques': 'No nearby mosques available',
      'prayer_source': 'Source: Imam {name}',
      'jumuah_label': 'Friday Prayer at the Mosque',

      // Hijri months

      'hijri_muharram': 'Muharram',
      'hijri_safar': 'Safar',
      'hijri_rabi1': 'Rabi\' Al-Awwal',
      'hijri_rabi2': 'Rabi\' Al-Thani',
      'hijri_jumada1': 'Jumada Al-Ula',
      'hijri_jumada2': 'Jumada Al-Akhira',
      'hijri_rajab': 'Rajab',
      'hijri_shaban': 'Sha\'ban',
      'hijri_ramadan': 'Ramadan',
      'hijri_shawwal': 'Shawwal',
      'hijri_dhulqada': 'Dhul Qa\'da',
      'hijri_dhulhijja': 'Dhul Hijja',

      // Days & Gregorian months
      'day_mon': 'Monday',
      'day_tue': 'Tuesday',
      'day_wed': 'Wednesday',
      'day_thu': 'Thursday',
      'day_fri': 'Friday',
      'day_sat': 'Saturday',
      'day_sun': 'Sunday',
      'month_jan': 'January',
      'month_feb': 'February',
      'month_mar': 'March',
      'month_apr': 'April',
      'month_may': 'May',
      'month_jun': 'June',
      'month_jul': 'July',
      'month_aug': 'August',
      'month_sep': 'September',
      'month_oct': 'October',
      'month_nov': 'November',
      'month_dec': 'December',

      // Feed Screen
      'feed_title': 'Posts & Updates',
      'tab_all': 'All',
      'tab_followed': 'Following',
      'unsave_post_success': 'Post removed from saved items',
      'save_post_success': 'Post saved successfully ✓',
      'feed_load_posts_failed': 'Failed to load posts',
      'no_posts_category': 'No posts in this category',
      'no_posts_followed': 'No posts from followed mosques and imams yet',
      'feed_no_followed_title': 'Not following any mosque or imam yet',
      'feed_no_followed_desc': 'Follow nearby mosques and their imams to see their posts here directly.',
      'feed_guest_title': 'Member-only Feature',
      'feed_guest_desc': 'Create an account to follow mosques and see their posts here.',
      'feed_elapsed_minute': '{count}m ago',
      'feed_elapsed_hour': '{count}h ago',
      'feed_elapsed_day': '{count}d ago',
      'feed_like_tooltip': 'Like',
      'feed_comment_tooltip': 'Comment',
      'feed_save_tooltip': 'Save Post',
      'feed_unsave_tooltip': 'Unsave Post',
      'feed_share_tooltip': 'Share',
      'feed_general_post': 'General',
      'cat_all': 'All',
      'cat_nearby': 'Nearby',
      'cat_lessons': 'Lessons',
      'cat_announcements': 'Announcements',
      'cat_activities': 'Activities',

      // Mosque Details Screen
      'mosque_load_error': 'Error loading mosque data',
      'mosque_not_found': 'Mosque not found',
      'mosque_share_copied': 'Mosque name copied',
      'mosque_unfollow_snack': 'Unfollowed "{name}"',
      'mosque_follow_snack': 'You are now following "{name}" ✓',
      'imam_unfollow_snack': 'Unfollowed imam',
      'imam_follow_snack': 'You are now following the imam ✓',
      'share': 'Share',
      'verified_mosque': 'Verified Mosque',
      'today_times': 'Today\'s Times',
      'imam_label': 'Imam: {name}',
      'no_times_today': 'No times set for today',
      'next_badge': 'Next',
      'prayer_times_tab': 'Prayer Times',
      'posts_tab': 'Posts',
      'about_mosque_tab': 'About',
      'prayer_times_error': 'Error loading prayer times',
      'no_prayer_times_today': 'No prayer times for today',
      'imam_updates_daily': 'The imam updates times daily',
      'prayer_source_imam': 'Source: Imam {name}',
      'jumuah_friday': 'Friday Prayer',
      'posts_load_failed': 'Failed to load posts',
      'no_mosque_posts': 'No posts from this mosque yet',
      'save_post_snack': 'Post saved ✓',
      'unsave_post_snack': 'Post removed from saved',
      'mosque_my_mosques': 'My Mosques',
      'mosque_follow_btn': 'Follow Mosque',
      'imam_follow_btn': 'Follow Imam',
      'imam_following_btn': 'Following Imam',
      'info_address': 'Address',
      'info_phone': 'Phone',
      'info_capacity': 'Capacity',
      'capacity_unit': 'worshippers',
      'info_city': 'City',
      'info_verified': 'Verification Status',
      'mosque_verified_yes': 'Verified Mosque ✓',
      'mosque_verified_no': 'Not Verified',
      'info_date_added': 'Date Added',

      // Post Details Screen
      'post_not_found': 'Post not found',
      'likes_count': '{count} likes',
      'comments_count': '{count} comments',
      'comments_title': 'Comments',
      'copy_post_snack': 'Post copied',
      'saved_snack': 'Saved ✓',
      'share_post': 'Share',
      'view_mosque': 'View Mosque',
      'event_details': 'Event Details',
      'event_date': 'Date',
      'event_time': 'Time',
      'event_location': 'Location',
      'comments_load_failed': 'Failed to load comments',
      'no_comments_yet': 'No comments yet. Be the first to comment!',
      'elapsed_now': 'Just now',
      'elapsed_minutes': '{count}m ago',
      'elapsed_hours': '{count}h ago',
      'elapsed_days': '{count}d ago',
      'comment_limit_error': 'Comment limit is 500 characters',
      'comment_hint': 'Write a comment...',
      'comment_added': 'Comment added successfully ✓',
      'comment_failed': 'Failed to add comment',
      'imam_mosque_label': 'Mosque Imam: {name}',
      'post_follow_btn': 'Follow',
      'post_following_btn': 'Following',
      'mosque_label_default': 'Mosque',

      // Register Screen
      'register_title': 'Create Account',
      'register_subtitle': 'Join Salati Qourbak and discover your mosque',
      'full_name': 'Full Name',
      'full_name_hint': 'Mohamed Ahmed',
      'full_name_required': 'Please enter your full name',
      'phone_optional': 'Phone Number (optional)',
      'confirm_password': 'Confirm Password',
      'confirm_password_required': 'Please confirm your password',
      'passwords_mismatch': 'Passwords do not match',
      'city_optional': 'City (optional)',
      'city_hint': 'Riyadh',
      'create_account_btn': 'Create Account',

      'continue_with_google': 'Continue with Google',
      'continue_with_apple': 'Continue with Apple',
      'already_have_account': 'Already have an account?',
      'sign_in_link': 'Sign In',
      'register_google_failed': 'Failed to sign up with Google',
      'register_apple_failed': 'Failed to sign up with Apple',

      // Profile screen extra keys
      'send_reset_email_label': 'Send Reset Link',
      'reset_email_sent_short': 'Sent ✓',
      'change_password': 'Change Password',
      'change_email': 'Change Email',
      'guest_user': 'Guest',
      'member_since': 'Member since',
      'sign_out_btn': 'Sign Out',
      'cancel_btn': 'Cancel',
      'edit_name': 'Edit Name',
      'new_name_hint': 'Enter name',
      'done_btn': 'Done',
      'app_name': 'Salati Qourbak',
      'app_legal': '© 2025 Salati Qourbak. All rights reserved.',
      'delete_desc_full': 'This action is permanent and will delete all your data. Are you sure?',
      'upgrade_account': 'Create Account',
      'guest_upgrade_prompt': 'Create an account to follow, interact, and benefit from all features.',
      'reset_email_sent_to': 'A password reset link will be sent to:\n{email}',
      'registered_user': 'Registered Member',
      'create_account_free': 'Create a Free Account',
      'guest_upgrade_card_desc': 'Save your preferences, follow prayer times, and connect with your favorite mosques across all devices.',
      'guest_exit_btn': 'Exit Guest Mode',
      'delete_account_confirm': 'Are you sure you want to permanently delete your account? This action cannot be undone.',
      
      // Location Permission Screen
      'loc_my_location': 'My Current Location',
      'loc_permission_failed': 'Failed to access current location. Please enter manually.',
      'loc_error': 'An error occurred while determining location.',
      'loc_title': 'Determine Your Location',
      'loc_desc': 'To display accurate prayer times and find nearby mosques, the app needs access to your location.',
      'loc_allow_btn': 'Continue',
      'loc_manual_btn': 'Enter Location Manually',
      'loc_select_city': 'Select Your City',
      'loc_select_city_desc': 'Select from available cities to view prayer times and nearby mosques.',
      'city_makkah': 'Makkah',
      'city_madinah': 'Madinah',
      'city_riyadh': 'Riyadh',
      'city_jeddah': 'Jeddah',
      'city_dubai': 'Dubai',
      'city_cairo': 'Cairo',
      'city_casablanca': 'Casablanca',
      'city_amman': 'Amman',

      // Home Screen extra
      'calc_method_label': 'Calculation Method: {method}',
      'calc_method_title': 'Calculation Method',
      'auto': 'Auto',
      'check_internet_retry': 'Check your internet connection and try again.',

      // Calculation Methods
      'method_1': 'Kuwait Meteorological Authority',
      'method_2': 'University of Islamic Sciences, Karachi',
      'method_3': 'Muslim World League (MWL)',
      'method_4': 'Umm Al-Qura, Makkah',
      'method_5': 'Egyptian General Authority of Survey',
      'method_7': 'Islamic Society of North America (ISNA)',
      'method_8': 'Gulf Region',
      'method_9': 'Diyanet İşleri Başkanlığı (Turkey)',
      'method_10': 'Algeria — Ministry of Religious Affairs',
      'method_11': 'National Verification Committee (Indonesia)',
      'method_12': 'Islamic Council of France (North)',
      'method_13': 'Omani Official Method',
      'method_14': 'Qatar — Ministry of Religious Affairs',
      'method_15': 'Singapore',
      'method_16': 'Union of Islamic Organisations in France (UOIF)',
      'method_17': 'Department of Islamic Development, Kuala Lumpur',
      'method_18': 'Morocco — Ministry of Awqaf',
      'method_19': 'Islamic University of UAE',
      'method_21': 'European Council for Fatwa and Research',
      'method_22': 'Islamic Association of North America (Canada)',
      'method_23': 'Official Calendar — Bangladesh',
      'method_24': 'Abu Dhabi Agriculture and Food Safety Authority',
    }



  };

  String translate(String key, {Map<String, String>? arguments}) {
    String value = _localizedValues[locale.languageCode]?[key] ?? key;
    if (arguments != null) {
      arguments.forEach((k, v) {
        value = value.replaceAll(k, v);
      });
    }
    return value;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) => SynchronousFuture<AppLocalizations>(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
